version: '3.8'

services:
  matrix-website:
    build: .
    container_name: matrix-website
    ports:
      - "8080:8080"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./icon.svg:/usr/share/nginx/html/icon.svg:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  website_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}
  nginx_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/docker-compose
